name: Validate the schemas and examples
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    name: validate
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Checkout Supporting Repos
        run: |
          git clone https://github.com/eurocris/CERIF-TG-Tools.git ../CERIF-TG-Tools
          git clone --branch=support-multiple-versions https://github.com/jdvorak001/openaire-cris-validator.git ../openaire-cris-validator
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Run the Validation Script
        run: ./tools/compile.sh
